name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Xcode environment
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.4.app

    # Install CocoaPods if your project uses it
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install
      working-directory: ./WorkFlowTest

    # Build the app and ensure the build is successful
    - name: Build app
      run: | 
        cd WorkFlowTest
        xcodebuild clean build -workspace WorkFlowTest.xcworkspace -scheme WorkFlowTest -sdk iphoneos CODE_SIGNING_ALLOWED=No
      continue-on-error: false
      shell: bash

    # Log current directory for debugging purposes
    - name: Log current directory
      run: pwd

    # Log directory contents for debugging purposes
    - name: Log root directory contents
      run: ls -al

    # Create a folder named 'ios_build' in the project root and save a text file after successful build
    - name: Create ios_build folder in root and save file
      if: success()
      run: |
        mkdir -p ${{ github.workspace }}/ios_build
        echo "Build successful on $(date)" > ${{ github.workspace }}/ios_build/build_info.txt
        echo "Folder ios_build and build_info.txt created."
      shell: bash

    # Log directory contents after creating folder for debugging
    - name: Log ios_build folder contents
      run: ls -al ${{ github.workspace }}/ios_build

    # Run tests (optional)
    - name: Run tests
      run: xcodebuild test -workspace WorkFlowTest.xcworkspace -scheme WorkFlowTest -destination 'platform=iOS Simulator,name=iPhone 14 Pro'

    # Archive the app (optional)
    - name: Archive app
      run: |
        xcodebuild archive \
          -workspace WorkFlowTest.xcworkspace \
          -scheme WorkFlowTest \
          -sdk iphoneos \
          -configuration Release \
          -archivePath ${{ github.workspace }}/WorkFlowTest.xcarchive

    # Upload the created folder as an artifact
    - name: Upload ios_build folder
      uses: actions/upload-artifact@v3
      with:
        name: build-folder
        path: ${{ github.workspace }}/ios_build

    # Optionally upload Xcode logs
    - name: Upload Xcode logs
      uses: actions/upload-artifact@v3
      with:
        name: xcode-logs
        path: ~/Library/Developer/Xcode/DerivedData
