name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Xcode environment
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.4.app

    # Install CocoaPods if your project uses it
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install
      working-directory: ./WorkFlowTest

    # Create a folder named 'ios_build' in the project root and save a text file
    - name: Create ios_build folder in root and save file
      run: |
        mkdir -p /WorkFlowTest/ios_build
        echo "CocoaPods installation successful on $(date)" > /WorkFlowTest/ios_build/build_info.txt
      shell: bash

    # Log root directory contents for debugging purposes
    - name: Log root directory contents
      run: ls -al ${{ github.workspace }}

    # Build the app and set DerivedData to a custom path inside the GitHub workspace
    - name: Build app
      run: | 
        cd WorkFlowTest
        xcodebuild clean build \
          -workspace WorkFlowTest.xcworkspace \
          -scheme WorkFlowTest \
          -sdk iphoneos \
          -derivedDataPath ${{ github.workspace }}/DerivedData \
          CODE_SIGNING_ALLOWED=No
      continue-on-error: false
      shell: bash

    # Run tests and save DerivedData to a custom path
    - name: Run tests
      run: |
        xcodebuild test \
          -workspace WorkFlowTest.xcworkspace \
          -scheme WorkFlowTest \
          -destination 'platform=iOS Simulator,name=iPhone 14 Pro' \
          -derivedDataPath ${{ github.workspace }}/DerivedData

    # Archive the app and use the custom DerivedData path
    - name: Archive app
      run: |
        xcodebuild archive \
          -workspace WorkFlowTest.xcworkspace \
          -scheme WorkFlowTest \
          -sdk iphoneos \
          -configuration Release \
          -archivePath ${{ github.workspace }}/WorkFlowTest.xcarchive \
          -derivedDataPath ${{ github.workspace }}/DerivedData

    # Upload the DerivedData folder as an artifact
    - name: Upload DerivedData folder
      uses: actions/upload-artifact@v3
      with:
        name: derived-data
        path: ${{ github.workspace }}/DerivedData

    # Upload the created folder as an artifact
    - name: Upload ios_build folder
      uses: actions/upload-artifact@v3
      with:
        name: build-folder
        path: ${{ github.workspace }}/ios_build

    # Optionally upload Xcode logs
    - name: Upload Xcode logs
      uses: actions/upload-artifact@v3
      with:
        name: xcode-logs
        path: ${{ github.workspace }}/DerivedData/Logs
